version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: apps/tweet-gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user-ms
      - tweet-ms
    environment:
      NODE_ENV: production
    env_file:
      - .env
      # add env vars
    networks:
      - tweet-net

  user-ms:
    build:
      context: .
      dockerfile: apps/user-ms/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - tweet-net

  tweet-ms:
    build:
      context: .
      dockerfile: apps/tweet-ms/Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    networks:
      - tweet-net

networks:
  tweet-net:
    driver: bridge
